[package]
name = "MEGA-Hackathon-25"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
notan = "0.12.1"
notan_egui = "0.12.1"
wasm-bindgen = "0.2.100"
rand = "0.8.5"